---
- name: Setup target host
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Add raspberry pi to inventory
      ansible.builtin.add_host:
        name: "{{ lookup('env', 'RASP5_HOST') }}"
        groups: targets
        ansible_user: "{{ lookup('env', 'RASP5_USER') }}"
        ansible_password: "{{ lookup('env', 'RASP5_PASS') }}"
        ansible_become_password: "{{ lookup('env', 'RASP5_PASS') }}"
        ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

- name: Reconcile HomeGPT Audio Streamer Service
  hosts: targets
  become: true
  gather_facts: false

  vars:
    service_name: homegpt-audio-streamer
    expected_hosts_entry: "{{ lookup('env', 'SERVER_IP') }}  {{ lookup('env', 'SERVER_URL') }}"

  tasks:
    - name: Ensure hosts entry is present
      ansible.builtin.lineinfile:
        path: /etc/hosts
        line: "{{ expected_hosts_entry }}"
        state: present

    - name: Check if service is running
      ansible.builtin.systemd:
        name: "{{ service_name }}"
        state: started
        enabled: true
      register: service_status

    - name: Display service status
      ansible.builtin.debug:
        msg: "Service {{ service_name }} is {{ service_status.status.ActiveState }}"
